name = "advent_of_code_2024"
version = "1.0.0"
target = "erlang"
gleam = ">= 1.5.0"

[dependencies]
gleam_stdlib = ">= 0.18.0 and < 2.0.0"
simplifile = ">= 2.2.0 and < 3.0.0"
glint = ">= 1.1.1 and < 2.0.0"
argv = ">= 1.0.2 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
